name: Run Netflix Data Pipeline

on:  
  push:  
    branches: [main]  
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:  
  run_pipeline:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: 3.10  

      - name: Install dependencies  
        run: pip install kaggle pandas  

      - name: Set up Kaggle API credentials  
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json  # Secure the file

      - name: Run Python script  
        run: python pipeline.py  
