name: Run Netflix Data Pipeline

on:
  push:  # Runs when you push changes to the repository
    branches:
      - main
  schedule:  # Runs automatically every day at midnight UTC
    - cron: "0 0 * * *" 
  workflow_dispatch:  # Allows manual execution

jobs:
  run-pipeline:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Pulls your repository to the runner

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Choose your Python version

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies (if you have a requirements.txt file)

      - name: Run Python Script
        run: python pipeline.py  # Executes your pipeline.py script
